name: Autobuild for Docker

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "${{ secrets.DOCKER_HOST }}"
      - name: Build the image
        run: |
          docker buildx build --push \
            --tag "${{ secrets.DOCKER_TAG }}" \
            --tag "${{ secrets.DOCKER_TAG }}:$BRANCH" \
            --platform linux/amd64 .
